name: podinfo
"on":
  workflow_dispatch: {}
  push:
    paths:
    - .alveus/demo/manifests
    branches:
    - main
jobs:
  prod:
    name: prod
    needs:
    - staging
    uses: ./.github/workflows/alveus-podinfo-prod.yml
    secrets: inherit
  staging:
    name: staging
    uses: ./.github/workflows/alveus-podinfo-staging.yml
    secrets: inherit
