name: main.yml
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          cache: true
      - run: make test

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    env:
      CI_RELEASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          version: v2025.10.8
          install: true
          cache: true
      - run: goreleaser release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ github.token }}
