---
name: release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
    - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Run goreleaser
      run: |
        git config --global --add safe.directory '*'
        if [ "${{ github.ref_type }}" = "tag" ]; then
          goreleaser release --clean
        else
          goreleaser release --clean --snapshot
        fi
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
